name: Netmonitor
options:
  bundleIdPrefix: com.blakemiller
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_FILE: Netmonitor/Info.plist
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0
    CODE_SIGN_STYLE: Automatic
    TARGETED_DEVICE_FAMILY: "1,2"
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES

packages:
  NetworkScanKit:
    path: NetworkScanKit

targets:
  Netmonitor:
    type: application
    platform: iOS
    sources:
      - path: Netmonitor
        excludes:
          - "**/.gitkeep"
          - "**/CLAUDE.md"
          - "**/AGENTS.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.blakemiller.netmonitor
        CODE_SIGN_ENTITLEMENTS: Netmonitor/Netmonitor.entitlements
        INFOPLIST_FILE: Netmonitor/Info.plist
    info:
      path: Netmonitor/Info.plist
      properties:
        CFBundleName: NetMonitor
        CFBundleDisplayName: NetMonitor
        UILaunchScreen:
          UIColorName: LaunchScreenBackground
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSLocalNetworkUsageDescription: NetMonitor needs local network access to discover devices on your network, connect to the NetMonitor Mac companion app, and perform network diagnostics.
        NSLocationWhenInUseUsageDescription: NetMonitor needs location access to display your current WiFi network name (SSID). Your location is never stored or shared.
        NSBonjourServices:
          - _netmon._tcp
          - _services._dns-sd._udp
        UIBackgroundModes:
          - fetch
          - processing
        BGTaskSchedulerPermittedIdentifiers:
          - com.blakemiller.netmonitor.refresh
          - com.blakemiller.netmonitor.sync
    dependencies:
      - target: NetmonitorWidget
        embed: true
        codeSign: true
      - package: NetworkScanKit

  NetmonitorWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: NetmonitorWidget
        excludes:
          - "**/.gitkeep"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.blakemiller.netmonitor.widget
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: NetMonitor Widget
        SKIP_INSTALL: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
        SWIFT_EMIT_LOC_STRINGS: YES
    info:
      path: NetmonitorWidget/Info.plist
      properties:
        CFBundleDisplayName: NetMonitor Widget
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension

  NetmonitorTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: NetmonitorTests
        excludes:
          - "**/.gitkeep"
    dependencies:
      - target: Netmonitor
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.blakemiller.netmonitor.tests
        GENERATE_INFOPLIST_FILE: YES

  NetmonitorUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: NetmonitorUITests
        excludes:
          - "**/.gitkeep"
    dependencies:
      - target: Netmonitor
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.blakemiller.netmonitor.uitests
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: Netmonitor

schemes:
  Netmonitor:
    build:
      targets:
        Netmonitor: all
        NetmonitorWidget: all
        NetmonitorTests: [test]
        NetmonitorUITests: [test]
    test:
      targets:
        - NetmonitorTests
        - NetmonitorUITests
